adicionando melhorias na aplicação para o deploy ser mais rápido

diff --git a/.github/workflows/prod.yml b/.github/workflows/prod.yml
--- a/.github/workflows/prod.yml
+++ b/.github/workflows/prod.yml
@@ -18,6 +18,13 @@ jobs:
           distribution: temurin
           java-version: 17
 
+      - name: Cache Maven packages
+        uses: actions/cache@v3
+        with:
+          path: ~/.m2/repository
+          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+          restore-keys: ${{ runner.os }}-maven
+
       - name: Build project
         run: mvn clean install
 
@@ -29,13 +36,19 @@ jobs:
 
       - name: Push Docker image
         run: docker push ${{ secrets.DOCKER_USERNAME }}/gestao_vagas
+        
   deploy:
       needs: build
       runs-on: self-hosted
       steps:
-          - name: Pull image docker hub
-            run: docker pull ${{ secrets.DOCKER_USERNAME }}/gestao_vagas:latest
-          - name: remove container
-            run: docker rm -f 
-          - name: Run docker container gestao-vagas
-            run: docker run -d -p 8080:8080 -e DATABASE_URL=${{ secrets.DATABASE_URL }} -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} --name gestao-vagas ${{ secrets.DOCKER_USERNAME }}/gestao_vagas
+        - name: Pull image docker hub
+          run: docker pull ${{ secrets.DOCKER_USERNAME }}/gestao_vagas:latest
+        - name: Remove container if exists
+          run: docker rm -f gestao-vagas || echo "Container not found, skipping removal"
+        - name: Run docker container gestao-vagas
+          run: docker run -d -p 8080:8080 \
+            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
+            -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
+            -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
+            --name gestao-vagas \
+            ${{ secrets.DOCKER_USERNAME }}/gestao_vagas:latest
